- job:
    description: Operator integration tests
    name: zuul-operator-functional
    abstract: true
    run:
      - playbooks/zuul-operator-functional/run.yaml
      - playbooks/zuul-operator-functional/test.yaml
    post-run: playbooks/zuul-operator-functional/post.yaml
    vars:
      # We disable userland-proxy to enable scheduler deployement to connect to the gearman service
      # see: https://github.com/eclipse/che/issues/8134
      docker_userland_proxy: false
      container_runtime: docker
      minikube_version: v1.33.1

- job:
    description: Operator integration tests with Kubernetes
    name: zuul-operator-functional-k8s
    parent: zuul-operator-functional
    pre-run: playbooks/zuul-operator-functional/pre-k8s.yaml
    nodeset: ubuntu-noble
    vars:
      namespace: 'default'

- job:
    description: Image and buildset registry job
    name: zuul-operator-build-image
    parent: opendev-build-container-image
    allowed-projects: stackhpc/zuul-operator
      - python-builder-3.11-bookworm-container-image
      - python-base-3.11-bookworm-container-image
    provides:
      - zuul-operator-container-image
    vars: &image_vars
      zuul_work_dir: "{{ zuul.projects['opendev.org/zuul/zuul-operator'].src_dir }}"
      promote_container_image_method: intermediate-registry
      promote_container_image_job: zuul-operator-upload-image
      container_command: docker
      container_images:
        - context: .
          container_filename: build/Dockerfile
          registry: quay.io
          repository: quay.io/zuul-ci/zuul-operator
          tags:
            # If zuul.tag is defined: [ '3', '3.19', '3.19.0' ].  Only works for 3-component tags.
            # Otherwise: ['latest']
            "{{ zuul.tag is defined | ternary([zuul.get('tag', '').split('.')[0], '.'.join(zuul.get('tag', '').split('.')[:2]), zuul.get('tag', '')], ['latest']) }}"

- secret:
    name: zuul-operator-registry-credentials
    data:
      quay.io:
        username: zuul-ci+opendevzuul
        password: !encrypted/pkcs1-oaep
          - R7XzsGx4q6LO5IQtTrISOmedzaWqIoJIlMpzwqrMyXPW/6y1BAFXmZoKvUrik9/fuhN+3
            43bxAR251GdodcDMeszGHJ3POuyV5ZqUqouKVbdWvEZ8UzKzQ2A6HN/sc/z6DzqZcfbi1
            6SfnWFhLTWl9f9yPaLkrOIaYY4xZZ8wn1D1wvMM3XZ580X/cjjJi5FCPq4iw+FZTrQssi
            jHMlwRiGpWHFlcd46xSItCwXTBv0O4xXoYkHn6StMakXIebraK28iBDQRPocQajfYuPF0
            ZIyDNXb72WcXZ5ruM5JVEbuqD29qQZUxKjGNF4lZyIz/fJW7fh17pxOX3wtJYBdntZKTd
            bJQsVkUJ3xr5R3DhO5e8U1TPn4lCWQ4eLzCMWt7Poo7+ivHMkrlahqv1LkIwoLdG76IU8
            I2HSaGa4CTl+ijVsf0kJBxnNiA64kQGVchX1obC7C1QQN4etumCcHDNwocoG0g8DaA2rX
            1VFVnCwTKOWY0S/qF+Jv3uAOIt9MOdFANmk3DR+b7hWT0SaDg7/lP03L6Z9cDcoF2FUqe
            M1+0oxX5L5da+pGcONCBIU2lHhFKLjspSTjsLuG/ipx9DXnldGXmruH5TFrN88ceoT+fR
            MtlGGWNBLqV0Q1QHkHZOPBlbz4/FQ/QzkKmEA2DOELzwSyjR4K4U8X2WlPco/A=
        api_token: !encrypted/pkcs1-oaep
          - noles77Ag87BegYa3HbRcLRT9z99HML5NR0DtcjbWbF1megRJh/l7KRrU8Y9qEHuXo82Q
            LRnhfiTGHXuHYR+P8KJVDOV1RZLJzDSI6MxNdS7+at8vi2RiXhR5K56xFeCiCfbbmwUHh
            xgvt1Tp2QBgVQKOY/SdT3rUh9A6+7510roOocKnW6aOJxTZafdE4t9J92t6FAPlboC3L+
            lcvgbxEnajY+kVBaa8KSmU7zQkxyHSpTTi1VnUCCZXcy0ljTYXIbZYO/WDKepudQmknDy
            QwdMm4MyQDPRcIaw80RakJSPfBmYC0IyGEeN6mC5nmrgcX83owHawS2yMEdM3+wPeSN22
            0Q6htKJ084JsDoz9BDYfoPhSpaWDbaNjDgp5GqGpX8TdtAcOVt175VA2xbFDeUxyV8aMa
            t2Uuf1WU0ixTd+JpqRwNIj58UZ7ng8Uiy55D1OL1U9jqxBn+E0WrxnMRhCVRHaZktp0FW
            ZDMczgKE8gs+5m7xjgBNiVkctgR43ocHCXxAgvb5BSzaSj+n7mjIoLUKFRzQKzzpKlpLc
            20zmYoB2W7Va85pEEnwmsKgGG++jsu9Zltzlr1WgkScWIO1/RatPTTKZedXFTILPV4PT6
            e+cQdaOI/U/nW/9ejRIrXaqMu6yhAp5w/19HBpCsaa0ZGWgKRMp7UdQv2sNWTM=

- job:
    description: Build container images and upload.
    name: zuul-operator-upload-image
    parent: opendev-upload-container-image
    allowed-projects: stackhpc/zuul-operator
    secrets:
      name: container_registry_credentials
      secret: zuul-operator-registry-credentials
      pass-to-parent: true
    provides:
      - zuul-operator-container-image
      - python-builder-3.11-bookworm-container-image
      - python-base-3.11-bookworm-container-image
    vars: *image_vars

- job:
    description: Promote previously uploaded images.
    name: zuul-operator-promote-image
    parent: opendev-promote-container-image
    allowed-projects: zuul/zuul-operator
    secrets:
      name: container_registry_credentials
      secret: zuul-operator-registry-credentials
      pass-to-parent: true
    nodeset:
      nodes: []
    vars: *image_vars

- project:
    check:
      jobs:
        - nox-linters
        - zuul-nox-docs
        - zuul-operator-build-image
        - zuul-operator-functional-k8s:
            dependencies: zuul-operator-build-image
    gate:
      jobs:
        - nox-linters
        - zuul-nox-docs
        - zuul-operator-upload-image
        - zuul-operator-functional-k8s:
            dependencies: zuul-operator-upload-image
    promote:
      jobs:
        - zuul-promote-nox-docs
        - zuul-operator-promote-image
    release:
      jobs:
        - zuul-operator-upload-image:
            vars:
              <<: *image_vars
              upload_container_image_promote: false
