apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/component: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zuul
      app.kubernetes.io/component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: zuul
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: zuul_db
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_USER
              value: "zuul"
          image: mariadb:10.10
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: var-lib-mysql
      hostname: mysql
      restartPolicy: Always
      volumes:
        - name: var-lib-mysql
          persistentVolumeClaim:
            claimName: var-lib-mysql

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/component: mysql
  name: mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/component: mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: zuul
    app.kubernetes.io/component: mysql
  name: var-lib-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi