apiVersion: operator.zuul-ci.org/v1alpha2
kind: Zuul
metadata:
  name: zuul
spec:
  executor:
    count: 1
    # sshkey:
    #   secretName: executor-secrets
  scheduler:
    config:
      secretName: zuul-tenant-config
  launcher:
    config:
      secretName: zuul-nodepool-config
  web:
    count: 1
  connections:
    github:
      driver: github
      app_id: 382716
      app_key: /gh-keys/gh-key.pem
      secretName: github-secrets
  database:
    allowUnsafeConfig: True
    secretName: mariadb-secret
