apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zuul-permissions
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - apply

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zuul-perms-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zuul-permissions
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default